-- Reusable invite links generated by admin for dealer onboarding
CREATE TABLE IF NOT EXISTS dealer_invites (
  id         text PRIMARY KEY,
  code       text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  used_at    timestamptz,
  used_by    text REFERENCES users(id)
);
